### ISSUE TITLE
Crash when trying to open the HUD editor

### ISSUE THREAD

**Issue by MartinSVK12** [ToufouMaster/BTWaila#15]
btwaila 1.1.1-7.2-pre2, bta 7.2pre2
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.core.world.World.getBlockId(int, int, int)" because "tileEntity.worldObj" is null
    at toufoumaster.btwaila.gui.components.AdvancedInfoComponent.drawFunctionalBlocksData(AdvancedInfoComponent.java:108)
    at toufoumaster.btwaila.gui.components.AdvancedInfoComponent.renderBlockOverlay(AdvancedInfoComponent.java:81)
    at toufoumaster.btwaila.gui.components.AdvancedInfoComponent.renderPreviewPost(AdvancedInfoComponent.java:71)
    at toufoumaster.btwaila.gui.components.WailaTextComponent.renderPreview(WailaTextComponent.java:125)
    at net.minecraft.client.gui.GuiHudDesigner.drawHudComponents(GuiHudDesigner.java:289)
    at net.minecraft.client.gui.GuiHudDesigner.drawScreen(GuiHudDesigner.java:239)
    at net.minecraft.client.render.WorldRenderer.updateCameraAndRender(WorldRenderer.java:575)
    at net.minecraft.client.Minecraft.run(Minecraft.java:891)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ToufouMaster** [comment]
I think this issue was resolved with pull request #16
